### ISSUE TITLE
Bad syntax in default.nix file

### ISSUE THREAD

**Issue by cpjolicoeur** [RocketPuppy/Retrograde#2]
https://github.com/RocketPuppy/Retrograde/blob/7c29d62ea8d6bdeb42f0f19ead8fd468d15bc16d/default.nix#L31

I'm pretty sure there is bad nix syntax here (missing a closing `};`).  I think I know where it is meant to go, but I figured I'd just post here and let you make the correction to ensure correctness.

**Comment by RocketPuppy** [comment]
I think this is fixed in master now.
